main:
  - {name: 首页, url: '/', weight: 10}
  - {name: 关于, url: '/about/', weight: 20}
  - {name: 研究方向, url: '/research/', weight: 30}
  - {name: 论文发表, url: '/publications/', weight: 40}
  - {name: 项目, url: '/projects/', weight: 50}
  - {name: 简历, url: '/cv/', weight: 60}
  - {name: 联系方式, url: '/contact/', weight: 70}
